version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_tasks_manager
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tasks_manager
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: tasks_manager
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata: 
    driver: local

